---
# handlers file for demo_role
# ---
# - name: unshut interface
#   ios_config:
#     lines:
#       - "interface e0/2"
#       - "no shutdown"

# - name: Display ios_facts
#   set_fact: 
#     interface_status: "{{ ansible_facts['net_interfaces']['Ethernet0/2']['lineprotocol'] }}"