---
- name: ios_command_prompt_demo
  hosts: ios
  gather_facts: no
  tasks:
    - name: show version
      ios_command:
        commands: 
          - command: 'clear counters e0/0' 
            prompt: 'Clear "show interface" counters on this interface \[confirm\]'
            answer: 'y'
      register: clear_counter_output
    
    - name: show interface
      ios_command:
        commands: 
          - command: 'show interface e0/0'
      register: interface_status_output

    - name: print output
      debug:
        var: interface_status_output.stdout_lines