---
- name: Demo on ios_config after
  hosts: ios
  gather_facts: no
  tasks:
    - name: Configure interface
      cisco.ios.ios_config:
        lines:
          - description This is a demo interface
          - ip address 10.10.10.1 255.255.255.0
          - no shutdown
        parents:
          - interface e0/1
      register: output

    - name: Print the result
      debug:
        msg: "{{ output }}"

    - name: Configure multiple interface
      cisco.ios.ios_config:
        lines:
          - ip helper-address {{ dhcp_server_1 }}
          - ip helper-address {{ dhcp_server_2 }}
        parents:
          - interface {{item}}
      loop:
        - e0/1
        - e0/2
      register: output
            
    - name: Print the result
      debug:
        msg: "{{ output }}"
    