---
- name: Demo on Handlers
  hosts: ios
  gather_facts: no
  tasks:
    - name: Shutdown interface
      ios_config:
        lines:
          - "interface e0/2"
          - "shutdown"
        diff_against: running
      notify: 
        - unshut interface
    
    - name: Display ios_facts
      debug: 
        msg: "{{ ansible_facts }}"

  handlers:
    - name: unshut interface
      ios_config:
        lines:
          - "interface e0/2"
          - "no shutdown"

    - name: Display ios_facts
      set_fact: 
        interface_status: "{{ ansible_facts['net_interfaces']['Ethernet0/2']['lineprotocol'] }}"