---
- name: Demo on Ansible Strategies
  hosts: ios
  gather_facts: no
  serial:
    - 1
    - 2 
  tasks: 
    - name: show ip interface brief
      ios_command:
        commands: show ip interface brief
      register: show_ip_interface_brief
    
    - name: Wait for 5 seconds
      ansible.builtin.wait_for:
        timeout: 5
        state: started

    - name: show version
      ios_command:
        commands: show version
      register: show_version